# Gradle Properties
org.gradle.jvmargs = -Xmx3G
org.gradle.daemon = false
org.gradle.cache.cleanup = false

# Mod Properties
maven_group = ch.endte
mod_id = syncmatica
mod_name = Syncmatica
mod_file_name = syncmatica-fabric

# Mod Version
mod_version = 0.3.20

# Dependencies (malilib / litematica)
malilib_version = 0.28.10
litematica_version = 0.27.11

# Minecraft, Fabric Loader and API and mappings versions
minecraft_version = 26.1.2
minecraft_version_out = 26.1.2

fabric_loader_version = 0.19.3
mod_menu_version = 18.0.0
fabric_api_version = 0.154.2+26.1.2

# Luck Permissions API
fabric_permissions_api_version = 0.7.0
