# Gradle Properties
org.gradle.jvmargs = -Xmx3G
org.gradle.daemon = false
org.gradle.cache.cleanup = false

# Mod Properties
maven_group = ch.endte
mod_id = syncmatica
mod_name = Syncmatica
mod_file_name = syncmatica-fabric

# Mod Version
mod_version = 0.3.15

# Dependencies (malilib, litematica)
malilib_version = 1.21.9-0.26.1
litematica_version = 1.21.9-0.24.0

# Minecraft, Fabric Loader and API and mappings versions
minecraft_version_out = 1.21.9
minecraft_version = 1.21.9
mappings_version = 1.21.9+build.1

fabric_loader_version = 0.17.2
mod_menu_version = 15.0.0-beta.3
fabric_api_version = 0.133.14+1.21.9

# Luck Permissions API
fabric_permissions_api_version = 0.4.1
