# Gradle Properties
org.gradle.jvmargs = -Xmx3G
org.gradle.daemon = false
org.gradle.cache.cleanup = false

# Mod Properties
maven_group = ch.endte
mod_id = syncmatica
mod_name = Syncmatica
mod_file_name = syncmatica-fabric

# Mod Version
mod_version = 0.3.18

# Dependencies (malilib / litematica)
malilib_version = 670d65c40c
litematica_version = eb36a0f574

# Minecraft, Fabric Loader and API and mappings versions
minecraft_version_out = 26.2-rc-1
minecraft_version = 26.2-rc-1

fabric_loader_version = 0.19.3
mod_menu_version = 20.0.0-alpha.1
fabric_api_version = 0.152.0+26.2

# Luck Permissions API
fabric_permissions_api_version = 0.7.0
